apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
  namespace: {{ .Values.argo-workflows }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      serviceAccountName: argo
      containers:
        - name: workflow-controller
          image: argoproj/workflow-controller:v3.4.0 # Update version as needed
          ports:
            - containerPort: 9090
